(* ::Package:: *)

(* ::Input:: *)
(*(* =========================================================*)*)
(*(* PACKAGE                                                  *)*)
(*(* =========================================================*)*)
(**)
(*(* :Title:TwoHedgehogs*)*)
(*(* :Context:TwoHedgehogs`*)*)
(*(* :Author:Alessio Cangini*)(* :Summary:Visualization tools for the two-hedgehog Riemann map.*)*)
(*(* :Copyright:...*)*)
(*(* :Package Version:1.0*)*)
(*(* :Mathematica Version:13.0*)*)
(*(* :History:Created July 21, 2026.*)*)
(**)
(**)
(**)
(**)
(*BeginPackage["TwoHedgehogs`"]*)
(**)
(*uniformizationValue::usage="uniformizationValue[t,s,p] gives the absolute value of the Riemann map on the unit circle.";*)
(**)
(*auxiliaryAngle::usage="auxiliaryAngle[s,p] returns the auxiliary angle used in the branch point formulas.";*)
(**)
(*realQuillParameter::usage="realQuillParameter[s,p] gives the parameter t_r.";*)
(**)
(*complexQuillParameter::usage="complexQuillParameter[s,p] gives the parameter t_c.";*)
(**)
(*domainGraphic::usage="domainGraphic[s,p,a] draws the unit-circle parameterization.";*)
(**)
(*hedgehogGraphic::usage="hedgehogGraphic[s,p,a] draws the corresponding hedgehog.";*)
(**)
(*profileGraphic::usage="profileGraphic[s,p,a] plots |\[CapitalPsi](e^{it})|.";*)
(**)
(*hedgehogAnimation::usage="hedgehogAnimation[] returns the interactive Manipulate.";*)
(**)
(*Begin["`Private`"]*)
(*(* =========================================================*)*)
(*(* MATHEMATICAL FUNCTIONS                                   *)*)
(*(* =========================================================*)*)
(*(*Absolute value of the Riemann map on the unit circle*)*)
(*uniformizationValue[t_,s_,p_]:=(2-2 Cos[t])^(p/2) (2-2 Cos[t-s])^(1-p/2);*)
(*(*Angle function appearing in Subscript[t, r] and Subscript[t, c]*)*)
(*auxiliaryAngle[s_,p_]:=ArcSin[(p-1) Sin[s/2]];*)
(*(*Definition of the functions tr and tc*)*)
(*realQuillParameter[s_,p_]:=s/2+auxiliaryAngle[s,p];*)
(*complexQuillParameter[s_,p_]:=s/2+Pi-auxiliaryAngle[s,p];*)
(**)
(*(* =========================================================*)*)
(*(* GRAPHICS                                                 *)*)
(*(* =========================================================*)*)
(*(*Domain of the Riemann parameterization*)*)
(*domainGraphic[s_,p_,a_]:=Module[{tr,tc},*)
(*tr=realQuillParameter[s,p];*)
(*tc=complexQuillParameter[s,p];*)
(*Graphics[{*)
(*Black,Circle[],*)
(*(*Thick,Line[{{0,0},{1,0}}],Line[{{0,0},{Cos[s],Sin[s]}}],Line[{{0,0},{Cos[a],Sin[a]}}],*)*)
(*Orange,PointSize[Large],Point[{{1,0},{Cos[s],Sin[s]}}],*)
(*Text[Style[Superscript["e", "is" ],16,Orange,Bold],{Cos[s],Sin[s]},{0,-1.5}],*)
(*Purple,PointSize[Large],Point[{{Cos[tr],Sin[tr]},{Cos[tc],Sin[tc]}}],*)
(*Text[Style[Superscript["e", "i" Subscript["t","r"]],16,Purple,Bold],{Cos[tr],Sin[tr]},{0,-1.5}],*)
(*Text[Style[Superscript["e", "i" Subscript["t","c"]],16,Purple,Bold],{Cos[tc],Sin[tc]},{0,-1.5}],*)
(*Green,PointSize[Large],Point[{Cos[a],Sin[a]}]},*)
(*PlotRange->1.25,*)
(*Axes->True,*)
(*AxesOrigin->{0,0},*)
(*AspectRatio->1,*)
(*ImagePadding->15]*)
(*];*)
(*(*Graphic representation of the hedgehog*)*)
(*hedgehogGraphic[s_,p_,a_]:=Module[{tr,tc,r1,r2,point},*)
(*tr=realQuillParameter[s,p];*)
(*tc=complexQuillParameter[s,p];*)
(*r1=uniformizationValue[tr,s,p];*)
(*r2=uniformizationValue[tc,s,p];*)
(*point=If[a<s,{uniformizationValue[a,s,p],0},uniformizationValue[a,s,p] {Cos[p Pi],Sin[p Pi]}];*)
(*Graphics[*)
(*{Thick,Line[{{0,0},{r1,0}}],Line[{{0,0},r2 {Cos[p Pi],Sin[p Pi]}}],*)
(*Orange,PointSize[Large],Point[{0,0}],*)
(*Purple,PointSize[Large],Point[{{r1,0},r2 {Cos[p Pi],Sin[p Pi]}}],*)
(*Text[Style[Subscript["z","r"],16,Purple,Bold],{r1,0},{0,-1.5}],*)
(*Text[Style[Subscript["z","c"],16,Purple,Bold],r2 {Cos[p Pi],Sin[p Pi]},{0,-1.5}],*)
(*Green,PointSize[Large],Point[point]},*)
(*PlotRange->4,*)
(*Axes->True,*)
(*AxesOrigin->{0,0},*)
(*AspectRatio->1,*)
(*ImagePadding->15]];*)
(*profileGraphic[s_,p_,a_]:=Module[{tr,tc,r1,r2},*)
(*tr=realQuillParameter[s,p];*)
(*tc=complexQuillParameter[s,p];*)
(*r1=uniformizationValue[tr,s,p];*)
(*r2=uniformizationValue[tc,s,p];*)
(*Show[*)
(*(*Plot[uniformizationValue[t,s,p],{t,0,2 Pi},PlotRange->{{0,2 Pi},{-.25,4.5}},(*PlotTheme->"Scientific",*),AxesLabel->{Style["t",16],Style["f(t)",4]},PerformanceGoal->"Quality"],*)*)
(*Plot[uniformizationValue[t,s,p],{t,0,2 Pi},PlotRange->{{0,2 Pi},{-0.25,4.5}},Frame->True,Axes->False,FrameLabel->{Style["Parameter t",16],Style["f(t)",16]},LabelStyle->Directive[16],PerformanceGoal->"Quality"],*)
(*Graphics[{*)
(*Orange,PointSize[Large],Point[{s,uniformizationValue[s,s,p]}],*)
(*Purple,PointSize[Large],Point[{{tr,r1},{tc,r2}}],*)
(*Text[Style[Subscript["z","r"],16,Purple,Bold],{tr,r1},{0,-1.5}],*)
(*Text[Style[Subscript["z","c"],16,Purple,Bold],{tc,r2},{0,-1.5}],*)
(*Green,PointSize[Large],Point[{a,uniformizationValue[a,s,p]}]}]*)
(*]*)
(*];*)
(*(* =========================================================*)*)
(*(* ANIMATION                                                *)*)
(*(* =========================================================*)*)
(*hedgehogAnimation:=Manipulate[*)
(*GraphicsGrid[{{domainGraphic[s,p,a],hedgehogGraphic[s,p,a]},{SpanFromLeft,profileGraphic[s,p,a]}}],{{p,2/3,"p"},10^-6,1,Appearance->"Labeled"},{{s,Pi,"s"},0,2 Pi,Appearance->"Labeled"},{{a,Pi,"a"},0,2 Pi,Appearance->"Labeled"},SaveDefinitions->False,TrackedSymbols:>{p,s,a},SynchronousUpdating->False];*)
(*End[]*)
(*EndPackage[]*)
(*(*Export["parametrization_2_quills.avi",hedgehogAnimation]*)*)



